IM LITERALY TRYING TO GET POINTS>>>
idk how to tho... i think i might need to white 100 lines of code
so here it goes
:)
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
Bring him to the hills 
IGHT well that was easy.... idk if it workied tho :/
